version: "3.9"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      ALLOWED_ORIGIN: http://localhost:3000
      REDIS_ADDR: redis:6379
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.production
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_WS: ws://localhost:8080
      REACT_APP_BACKEND_URL: http://localhost:8080
  