jobs:
  test:
    docker:
      - image: circleci/node
    working_directory: ~/chat-app/frontend
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test

