version: 2
jobs:
  build:
    working_directory: ~/chat-app/frontend
    docker:
      # specify the version you desire here
      - image: circleci/node

    environment:
      REACT_APP_BACKEND_WS: ws://localhost:8080
      REACT_APP_BACKEND_URL: http://localhost:8080

    steps:
      - checkout:
          path: ~/chat-app

      - run: npm test