version: 2
jobs:
  build:
    working_directory: ~/chat-app/frontend
    docker:
      # specify the version you desire here
      - image: circleci/node

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/chat-app

      - run: npm install
      - run: npm test