version: 2.1
jobs:
  frontend-tests:
    working_directory: ~/chat-app/frontend
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: Run installation
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - frontend-tests