version: 2.1

jobs:
  test-frontend:
    working_directory: ~/chat-app/frontend
    docker:
      - image: circleci/node
    environment:
      REACT_APP_BACKEND_WS: ws://localhost:8080
      REACT_APP_BACKEND_URL: http://localhost:8080
    steps:
      - checkout:
          path: ~/chat-app
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Testing
          command: npm test

  build-frontend-image:
    working_directory: ~/chat-app/frontend
    docker:
      - image: circleci/node
    steps:
      - run: echo "build-frontend-image"
  deploy-frontend-image:
    working_directory: ~/chat-app/frontend
    docker:
      - image: circleci/node
    steps:
      - run: echo "push-frontend-image"
  build-backend-image:
    working_directory: ~/chat-app/frontend
    docker:
      - image: circleci/node
    steps:
      - run: echo "build-backend-image"
  deploy-backend-image:
    working_directory: ~/chat-app/frontend
    docker:
      - image: circleci/node
    steps:
      - run: echo "push-backend-image"

workflows:
  build-production:
    jobs:
      - test-frontend:
          context: test
      - build-frontend-image:
          context: docker-hub
          requires: 
              - test-frontend
      - deploy-frontend-image:
          context: docker-hub
          requires:
              - test-frontend
              - build-frontend-image
      - build-backend-image:
          context: docker-hub
      - deploy-backend-image:
          context: docker-hub
          requires: 
              - build-backend-image